### ISSUE TITLE
[Grades] Placeholder N/D anziché NaN

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#102]
- [x] il testo "comunicazioni" della pagina bacheca dovrebbe essere incluso nella listview anzichè nella pagina xaml, così non viene incluso per quando non si hanno comunicazioni. EDIT: racchiudiamo tutto nella #105  
- [x] il CalendarDatePicker della pagina Assenze dovrebbe usare Min e Max date come quello dell'agenda
- [x] fixare layout pagina assenze
- [x] fixare placeholder no assenze e no valutazioni
da fare
- [ ] (valutazioni) quando non si hanno voti e non si possono calcolare medie, visualizzare il placeholder N/D anzichè NaN

**Comment by alessandrocaseti** [comment]
@Gabboxl la pagina valutazioni continua a non funzionare se non si hanno voti

**Comment by Gabboxl** [comment]
> @Gabboxl la pagina valutazioni continua a non funzionare se non si hanno voti

Sisi lo so, metterò a posto

**Comment by alessandrocaseti** [comment]
@Gabboxl si potrebbe rendere traducibile come stringa? (in inglese sarebbe N/A)

**Comment by Gabboxl** [comment]
> @Gabboxl si potrebbe rendere traducibile come stringa? (in inglese sarebbe N/A)

si
