### ISSUE TITLE
[Bacheca] (Fixare) Filtro comunicazioni per categoria

### ISSUE THREAD

**Issue by Gabboxl** [Gabboxl/ClassevivaPCTO#106]
Le comunicazioni senza categoria andranno ovviamente inserite in "Nessuna categoria"
-  [x] ~Implementare sticky titles per la categoria (no perchè le comunicazioni le ordiniamo sempre dalla più nuova, e poi si sta parlando di filtro, non di raggruppamento)~

**Comment by alessandrocaseti** [comment]
![Screenshot (254)](https://github.com/Gabboxl/ClassevivaPCTO/assets/90320229/d4c645c6-0ff1-4730-b600-b56a8cb5f06b)
![Screenshot (255)](https://github.com/Gabboxl/ClassevivaPCTO/assets/90320229/fd98d5e0-cadc-4895-89cf-2e6ddb47fbd0)
@Gabboxl smanettando col filtro ho riscontrato questi problemi, a volte inoltre la sezione news non viene mostrata anche se disponibile

**Comment by alessandrocaseti** [comment]
inoltre il filtro semba non funzionare proprio. A questo punto perchè non usare una semplice combobox invece che un input di testo? Oltre a questo bisogna aggiornare manualmente la pagina per rendere effettivo il filtro

**Comment by Gabboxl** [comment]
sì hai ragione, mi sono dimenticato di un bel po' di roba, domani metto a posto

**Comment by alessandrocaseti** [comment]
il problema persiste. Bisogna:

- eliminare l'elemento della combobox vuoto
- aggiungere un opzione della combobox "Nessuna categoria"
