### ISSUE TITLE
problemi con la combobox della lingua / cambio lingua inapp

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#113]
- vengono visualizzate solo italiano e inglese, le altre no
- inzialmente (primo avvio) la checkbox è vuota
- riavviando l'app la lingua non cambia

sarebbe meglio rimuovere il testo "Stati Uniti d'America, Italia" etc.. lasciamo solo Italiano / Inglese

**Comment by Gabboxl** [comment]
Strano, in debug funziona, in release no

**Comment by alessandrocaseti** [comment]
![Screenshot (197)](https://github.com/Gabboxl/ClassevivaPCTO/assets/90320229/1ce2f74f-0068-4caf-9727-cdbf9a27c6f4)

come dicevo nell'issue la combobox è vuota all'inizo

inoltre si potrebbero togliere le scritte dei nomi dei paesi? lasciamo solo il nome della lingua, ci dovrebbero essere le strings già tradotte

**Comment by Gabboxl** [comment]
> come dicevo nell'issue la combobox è vuota all'inizo
Questo lo metto a posto oggi

> inoltre si potrebbero togliere le scritte dei nomi dei paesi? lasciamo solo il nome della lingua, ci dovrebbero essere le strings già tradotte
La traduzione automatica include sempre il paese, però è comunque meglio metterlo perchè alcune lingue variano da paese a paese come l'inglese britannico/americano

**Comment by Gabboxl** [comment]
Ok il problema delle lingue visualizzare è legato al Microsoft Store che scarica le resources in base a quelle richieste dal dispositivo, quindi non tutte. https://stackoverflow.com/questions/40957295/how-to-always-install-all-localized-resources-in-windows-store-uwp-app

Vedrò se si possono installare tutte sempre in ogni caso

**Comment by Gabboxl** [comment]
Lingua selezionata fixata con https://github.com/Gabboxl/ClassevivaPCTO/commit/60c447f72042f5bb9dde60413642111b09f8c30d, rimane trovare il modo di includere tutte le lingue in release su microsoft store

**Comment by Gabboxl** [comment]
Il problema delle lingue incluse nel package potrebbe essere stato fixato con https://github.com/Gabboxl/ClassevivaPCTO/commit/f877703912f7ef6fe6e37a2f01c34ccfe34ab428, vedremo per il rilascio 1.1.0 come va

**Comment by alessandrocaseti** [comment]
Versione stable. Problema risolto: funziona tutto correttamente.

**Comment by Gabboxl** [comment]
il problema persiste

**Comment by alessandrocaseti** [comment]
@Gabboxl strano, sulla mia versione stable funzionano perfettamente le lingue

**Comment by Gabboxl** [comment]
> @Gabboxl strano, sulla mia versione stable funzionano perfettamente le lingue

hai ragione, ho fatto altri test da macchine virtuali con windows 10 ed effettivamente vengono scaricate le altre lingue, è un problema con qualcosa che ho fatto io a questo punto
