### ISSUE TITLE
Migliorare il design delle comunicazioni eliminate

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#114]
Migliorare il design delle comunicazioni eliminate

![Screenshot (196)](https://github.com/Gabboxl/ClassevivaPCTO/assets/90320229/c4a82358-6e9e-4c07-b9ea-149ed05c3f30)

- [x] Il testo "non disponibile" dovrebbe essere traducibile
- [x] Dovrebbe essere scritto in un'unica riga per preservare spazio ed evitare sproporzionamenti nella listview
- [x] non dovrebbe essere incluso di default, ma solo se "mostra comunicazioni inattive" è spuntato

**Comment by Gabboxl** [comment]
Sì hai ragione, mi sa che si è rotto qualcosa perchè prima funzionava il filtro

**Comment by Gabboxl** [comment]
@alessandrocaseti potresti controllare se vedi ancora le comunicazioni eliminate nella vista di default? a me sembra essere a posto

**Comment by alessandrocaseti** [comment]
@Gabboxl il design va bene ma la comunicazione si vede lo stesso anche senza spuntare la checkbox

**Comment by Gabboxl** [comment]
> @Gabboxl il design va bene ma la comunicazione si vede lo stesso anche senza spuntare la checkbox

Ah, non saprei come mettere a posto, da me il filtro funziona

**Comment by alessandrocaseti** [comment]
@Gabboxl il filtro adesso funziona, forse era un problema della mia scuola
