### ISSUE TITLE
KeyboardAccelerators nella login page

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#122]
Textbox username

- [ ]  Cliccando il tasto Invio il focus passa alla passwordbox
- [ ]  Cliccando il tasto -> il focus passa alla passwordbox

Passwordbox

- [ ]  Cliccando il tasto Invio viene premuto il bottone "Accedi"
- [ ]  Cliccando il tasto -> viene premuto il bottone "Accedi"
- [ ]  Cliccando il tasto <- il focus ritorna alla textbox username

**Comment by Gabboxl** [comment]
Ci ho pensato a questo all'inizio ma leggendo su internet in realtà in questa situazione non avrei dovuto usare i gli accelerators per effettuare il login. Perché in realtà esiste già il pulsante Tab per selezionare i vari campi. E fare quello che ho fatto con il pulsante Enter non è una buona pratica.

I pulsanti freccia servono già per muoversi nel testo dei campi. 

Lasciamo così com'è, altrimenti rischiamo di modificare un comportamento che gli altri si aspettano essere diverso
