### ISSUE TITLE
[Dashboard] migliorare layout, evitare widget troppo grandi

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#128]
![Screenshot (226)](https://github.com/Gabboxl/ClassevivaPCTO/assets/90320229/a324db9c-9d1f-408d-bb0b-bd4a433c2fe2)

**Comment by Gabboxl** [comment]
La scrollbar deve restare per schermi più piccoli, servirà anche quando aggiungeremo più widget. Metterò a posto la dimensione delle varie schede

**Comment by Gabboxl** [comment]
Sincero non so come mettere a posto questo problema, le ho provate tutte
mi sa che rimarrà aperto per prossime versioni

**Comment by alessandrocaseti** [comment]
io avevo pensato di rimuovere il mainscrollbar, tanto le listview dovrebbero avercelo già da loro. Per quando metteremo altri widget potremmo usare un pipspager come il menu start di win11

**Comment by Gabboxl** [comment]
la scrollbar sarà sempre necessaria in caso di finestre piccole perchè le schede vengono messe una sotto l'altra quando non c'è spazio. spostare i widget in diverse pagine del pipspager in base allo spazio disponibile credo sia stra difficile da implementare

**Comment by Gabboxl** [comment]
abbandonare l'idea dell'auto expading uniformgrid e utilizzare il grid standard + implementare dimensioni predefinite per i widget
