### ISSUE TITLE
[Settings\Agenda] possibilità di disattivare testo AGNT/AGHW e aggiungere un teachingtip per spiegarne il significato

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#135]

**Comment by Gabboxl** [comment]
Questo testo verrà tolto una volta inplementato l'issue delle icone, direi di chiuderlo

**Comment by Gabboxl** [comment]
https://github.com/Gabboxl/ClassevivaPCTO/issues/121 il testo lo toglieremo comunque senza possibilità di attivarlo in favore delle icone, è inutile e confusionario

**Comment by Gabboxl** [comment]
https://github.com/Gabboxl/ClassevivaPCTO/issues/121 il testo lo toglieremo comunque senza possibilità di attivarlo in favore delle icone, è inutile e confusionario
