### ISSUE TITLE
[Scrutini] Aggiornare headers

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#155]
sostituire i titoli documenti e report scolastici negli scrutini con i nuovi stickyheaders

**Comment by Gabboxl** [comment]
non credo si possa fare perchè sono due listview differenti contenenti elementi di tipologia diversa. non è possibile raggruppare  elementi di tipo diversi in un singolo listview, cosa che è richiesta dagli sticky headers

**Comment by alessandrocaseti** [comment]
allora bisogna aggiornare i titoli per essere consistenti, ci penserò io
