### ISSUE TITLE
[Overview] placeholder "nessuna nota"

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#158]
![Screenshot (228)](https://github.com/Gabboxl/ClassevivaPCTO/assets/90320229/e70a93f2-42b6-48e6-a9f3-d71939c91420)
viene mostrato il placeholder "nessuna nota"

**Comment by Gabboxl** [comment]
Hai una versione vecchia del codice probabilmente, l'ho fixato ieri

**Comment by alessandrocaseti** [comment]
> Hai una versione vecchia del codice probabilmente, l'ho fixato ieri

no, era con l'ultimo commit di eri, adesso provo con quello di oggi

**Comment by alessandrocaseti** [comment]
ok non viene più mostrato nell'overview ma non appare nemmeno nella pagina delle note
