### ISSUE TITLE
Traduzioni Crowdin OTA

### ISSUE THREAD

**Issue by Gabboxl** [Gabboxl/ClassevivaPCTO#162]
Implementare traduzioni OTA (over the air) da nuova libreria https://github.com/Gabboxl/crowdin-net-sdk

**Comment by alessandrocaseti** [comment]
@Gabboxl lo teniamo per la 1.3?

**Comment by Gabboxl** [comment]
https://devblogs.microsoft.com/ifdef-windows/use-a-custom-resource-markup-extension-to-succeed-at-ui-string-globalization/

https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.resources.customxamlresourceloader?view=winrt-22621

**Comment by Gabboxl** [comment]
https://github.com/DotNetPlus/ReswPlus

**Comment by Gabboxl** [comment]
https://www.c-sharpcorner.com/UploadFile/e4003e/how-to-create-and-use-a-customresource-in-xaml/

**Comment by Gabboxl** [comment]
@alessandrocaseti da ora in poi non useremo più il tag x:Uid, useremo il markup `{CustomResource nomeRisorsa}` per localizzare le varie proprietà
