### ISSUE TITLE
Aggiungere file risorse it-it\Untranslatable.resw per il changelog

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#168]

**Comment by alessandrocaseti** [comment]
@Gabboxl vorrei implementare il changelog in questo file, per richiamare le traduzioni devo sempre usare il metodo x:Uid?

**Comment by Gabboxl** [comment]
No perché x:bind prende soltanto da Resources.resw. devi usare il metodo che avevo messo da qualche parte con "x:bind helpers: " ecc...

Se non lo trovi te lo mando stasera 👍

**Comment by alessandrocaseti** [comment]
> No perché x:uid prende soltanto da Resources.resw. devi usare il metodo che avevo messo da qualche parte con "x:bind helpers: " ecc...
> 
> Se non lo trovi te lo mando stasera 👍

ci sono riuscito, ho guardato come hai fatto su fluentweather

**Comment by Gabboxl** [comment]
> ci sono riuscito, ho guardato come hai fatto su fluentweather

ok grande, va bene anche come hai fatto
comunque sappi che si può fare anche così https://gist.github.com/Gabboxl/e95ef1200bdd4858cb739f0d99969ba5

**Comment by alessandrocaseti** [comment]
> > ci sono riuscito, ho guardato come hai fatto su fluentweather
> 
> ok grande, va bene anche come hai fatto comunque sappi che si può fare anche così https://gist.github.com/Gabboxl/e95ef1200bdd4858cb739f0d99969ba5 direttamente nello xaml

ah ok, grazie
