### ISSUE TITLE
[Valutazioni] Aggiungere shimmer

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#172]
La pagina valutazioni è quella più lenta nel caricamento (nel mio caso fino a 6s) e quella più confusionaria da vedere quando i dati non sono ancora caricati. Per ovviare a ciò si possono usare gli shimmer del CommunityToolkit Labs.

https://github.com/CommunityToolkit/Labs-Windows/issues/390

In futuro potremmo integrarli anche nelle altre pagine, ma penso dovremmo implementarli solo nelle valutazioni per ora.

Nello specifico: 

- [x] Shimmer per i testi "Media totale", trimestre e pentamestre
- [x] Shimmer per conteggio valutazioni
- [x] Shimmer per il segmentedcontrol

## funzionamento
Gli shimmer saranno visibili solo al caricamento della **pagina**, ciò vuol dire che se l'utente aggiorna la pagina tramite il tasto refresh essi non verranno attivati.

**Comment by Gabboxl** [comment]
> La pagina valutazioni è quella più lenta nel caricamento (nel mio caso fino a 6s)

Davvero 6 secondi? Mi sa che c'è anche un problema a livello di caricamento allora. Proverò a vedere

**Comment by alessandrocaseti** [comment]
@Gabboxl in versione stable da store arriva fino ai 3. 6 secondi in debug. Comunque Ii problema penso sia legato alla connessione, gli shimmer risolvono tutto

**Comment by Gabboxl** [comment]
> @Gabboxl in versione stable da store arriva fino ai 3. 6 secondi in debug. Comunque Ii problema penso sia legato alla connessione, gli shimmer risolvono tutto

Si gli shimmer li aggiungiamo, ti illudono temporaneamente sulla presenza di dati però se si può risolvere il problema all'origine è meglio
