### ISSUE TITLE
[Assenze] rendere traducibili le motivazioni nelle assenze giustificate

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#175]

**Comment by Gabboxl** [comment]
purtroppo non è possibile renderle traducibili perchè vengono restituite dal server di spaggiari e non sono predicibili

**Comment by alessandrocaseti** [comment]
@Gabboxl non si può fare come con le note? Se la motivazione è A restituire ... etc?

**Comment by Gabboxl** [comment]
> @Gabboxl non si può fare come con le note e gli altri elementi delle assenze (AB01.. etc)? Si potrebbe fare che se la motivazione è A restituire ... e così via no?

allora ho guardato ancora un po' il codice dell'app dei professori, il problema è che non possiamo essere al 100% sicuri che se la motivazione è A la descrizione sia sempre "Problemi di salute"... il professore a quanto pare può aggiungere delle note personali alla motivazione.

La tipologia dell'evento AB01 ecc... è l'unico elemento costante di cui possiamo essere certi che non cambi.

Per ora chiudo l'issue come non pianificato, se dovesse cambiare qualcosa nella api poi lo metteremo a posto

**Comment by Gabboxl** [comment]
è cambiato qualcosa nella API? @alessandrocaseti

**Comment by alessandrocaseti** [comment]
> è cambiato qualcosa nella API? @alessandrocaseti 

volevo chiederti se potessi controllarlo tu, hanno fatto da poco un update bello grosso con tante nuove feature e un resign completo dell'interfaccia

**Comment by Gabboxl** [comment]
> > è cambiato qualcosa nella API? @alessandrocaseti
> 
> volevo chiederti se potessi controllarlo tu, hanno fatto da poco un update bello grosso con tante nuove feature e un resign completo dell'interfaccia

ok stasera provo a decompilare il nuovo apk e guardo cosa hanno fatto

**Comment by Gabboxl** [comment]
l'api è la stessa, non è cambiato nulla
