### ISSUE TITLE
[Valutazioni] colore background dinamico per i progressring

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#198]
Utilizzare un background dinamico per i progress ring delle valutazioni. In particolare, lo sfondo dovrebbe richiamare il colore principale, ovviamente con brightness ridotta per mantenere il contrasto. Non si possono utilizzare valori fissi date le palette e la possibile feature futura di creare schemi di colori customizzati. Quindi, dovremmo creare un converter che prenda il colore principale e lo abbassi di luminosità.

**Comment by Gabboxl** [comment]
cosa intendi per colore principale? il colore di sistema?

**Comment by alessandrocaseti** [comment]
> cosa intendi per colore principale? il colore di sistema?
> Non è più pulito lasciare il background trasparente dei progress ring?

nono, ad esempio il verde della sufficienza etc. Guarda i progressring dell'app di classeviva.

**Comment by Gabboxl** [comment]
ahh okay capito, non usandola più mi ero perso questo aggiornamento
vedremo come fare poi

**Comment by alessandrocaseti** [comment]
@Gabboxl c'è qualcosa che non va, guarda i testi che hanno come colore una qualsiasi themeresource come si comportano. Nel mio caso ogni volta che si va nella pagina voti i testi sono sempre più scuri (vale per tutta l'app), prendi come esempio il conteggio valutazioni, le icone nelle listview, nome e codice nelle settings e praticamente tutto. Inoltre se apro l'app in autonomia fuori da VS la nagivazione tra le pagine è come bloccata da qualcosa, l'unica pagina accessibile è quella delle impostazioni

**Comment by alessandrocaseti** [comment]
dovrebbere riguardare tutti i testi che hanno come foreground TextFillColorTertiaryBrush
