### ISSUE TITLE
login errato

### ISSUE THREAD

**Issue by Tian-MC** [Gabboxl/ClassevivaPCTO#2]
hey ciao, volevo provare il tuo programma, ma mi da questo errore:
io ho settato il mio account come custom (usando l'email come login e la password modificata), probabilmente questo e' il problema.

![image](https://user-images.githubusercontent.com/66381488/225955373-ec497641-6cf2-4118-938b-b95108ba65b8.png)

**Comment by Gabboxl** [comment]
Ciao! Stai utilizzando la versione pubblicata sul Microsoft Store oppure hai compilato l'app dal codice attuale?
Recentemente Spaggiari ha cambiato il metodo di accesso alle API e il fix non lo abbiamo ancora pubblicato sullo store.

**Comment by Gabboxl** [comment]
> Ciao, innanzitutto grazie! Finalmente qualcuno che risolve il problema dell'orrenda grafica di Spaggiari Web! Anche io ho provato a fare il login e mi dà lo stesso errore. L'app l'ho scaricata dal Microsoft Store. Ho scaricato la source, come faccio a compilare l'exe? C'è da usare Visual Studio Code?

Ciao, sinceramente non ci saremmo mai aspettati che qualcun'altro potesse trovare utile quest'app oltre a noi già adesso!

La versione con con il bug del login corretto (ovvero la 0.0.2) è in fase di approvazione sul Microsoft Store, ci vorrà qualche giorno.

Per compilare l'app ti servirà Visual Studio 2022 (quello con il logo viola).
Dall'installer di Visual Studio devi assicurarti di aver installato il pacchetto di sviluppo per la piattaforma desktop .NET e anche per la piattaforma UWP. 

Dopo aver installato il tutto, apri con Visual Studio la soluzione del progetto (il file .sln), nella barra in alto seleziona l'architettura del tuo PC (x64, ARM, ecc.), poi premi il pulsante con la freccia verde per iniziare la compilazione.

Così dovresti riuscire a compilare l'app per conto tuo.

Nei prossimi giorni scriverò una guida più dettagliata nel README comunque

**Comment by stepersy** [comment]
Perfetto, grazie mille! Penso che aspetterò l'uscita della versione sul Microsoft Store, perchè ho già Visual Studio Code installato sul mio PC e se ci installo Visual Studio mi si riempe troppo lo spazio sul disco (ho solo 256GB). Comunque ancora grazie, spero che questo progetto continui, avete il mio pieno supporto!

**Comment by Gabboxl** [comment]
> una domanda per vs2022. che linguaggi devo scaricare?

Per l'app abbiamo usato solo C#.

**Comment by stepersy** [comment]
Potresti fare un tutorial o una guida su come compilare l'app su Visual Studio, o potresti caricare anche l'exe dell'app delle release? Grazie!

**Comment by Gabboxl** [comment]
> Potresti fare un tutorial o una guida su come compilare l'app su Visual Studio, perchè non riesco a compilarla, cioè, mi si chiude subito dopo che la apro). Allego un video.

Mhh, questo sembra essere un bug durante il caricamento dell'account. Se l'app è stata installata dopo aver avviato la compilazione da Visual Studio vuol dire che è stata compilata correttamente. 

Riusciresti a riavviare l'app da Visual Studio selezionando la configurazione "Debug" e inviare lo screenshot dell'errore evidenziato da Visual Studio quando crasha l'app?
![image](https://user-images.githubusercontent.com/26819478/228353357-9d75d9a9-b4f4-4e52-96ad-54621740e323.png)

So che questo non è uno dei migliori modi per lavorare, nei prossimi giorni cercherò di migliorare la situazione.

Grazie :)


> Se no, potresti caricare l'exe dell'app nelle release? Grazie!

Il formato di rilascio per le app UWP è in pacchetto MSIX, ovvero non credo sia possibile distribuire l'app via soltanto file .exe.
Questo pacchetto è abbastanza complicato da installare manualmente per via di certificati che devono anch'essi essere installati, vedrò cosa si può fare anche riguardo a questo comunque.

**Comment by Gabboxl** [comment]
@stepersy a quanto pare il crash aveva a che fare con il calcolo della media e ora dovrebbe essere risolto, prova a ricompilare l'ultima versione dal branch `main`. fammi sapere :)

**Comment by stepersy** [comment]
@Gabboxl Quindi scarico lo .zip, lo apro e faccio il debug?

**Comment by Gabboxl** [comment]
> @Gabboxl Quindi scarico lo .zip, lo apro e faccio il debug, oppure posso fare direttamente "Apri in Visual Studio" e poi faccio il debug?

E' identico, con "Apri in Visual Studio" è più veloce :)

**Comment by stepersy** [comment]
Sisì, ho fatto così alla fine. Ha finito ed ora funziona. Però è normale che non carichi diverse sezioni? Tipo l'agenda, la bacheca e le assenze? E poi al posto delle lezioni di oggi carica tutti i voti...
![Screenshot 2023-03-29 162811](https://user-images.githubusercontent.com/94073410/228571286-45a5ac2b-e29a-4aae-886c-b0f622cf38b7.png)
![Screenshot 2023-03-29 162755](https://user-images.githubusercontent.com/94073410/228571298-06e2233d-f19c-4163-9c2c-bfd212ee76d3.png)
![Screenshot 2023-03-29 162743](https://user-images.githubusercontent.com/94073410/228571302-3e484783-092f-4f6a-a3bb-bf58bf959c5d.png)
![Screenshot 2023-03-29 162733](https://user-images.githubusercontent.com/94073410/228571304-63900986-e385-4bc1-b512-be549a6e7eae.png)

**Comment by Gabboxl** [comment]
@stepersy Sisì è normale, le sezioni mancanti le stiamo ancora implementando. Fra una o due settimane dovrebbero essere pronte. 
Il progetto è iniziato da poco e lo sviluppo su Windows non è così semplice come pensavamo.
 Comunque grazie per aver provato :))

**Comment by stepersy** [comment]
Ahhh, capisco perfettamente. Io non ne so niente di sviluppo, quindi ho solo da dirvi grazie a voi per il progetto che state portando avanti! Aspetto nuove release con nuove funzionalità :)

**Comment by Gabboxl** [comment]
Ciao a tutti, riguardo ai vari problemi di login è appena stata rilasciata sul [Microsoft Store](https://apps.microsoft.com/store/detail/classevivapcto/9PNST3M88D1S) la versione 0.0.4 che risolve i principali problemi di login.
Lo sviluppo delle altre sezioni sta procedendo e verranno rilasciate a breve.

Ora chiudo questo issue, se doveste incontrare altri problemi apritene pure un altro! Ciao : )
