### ISSUE TITLE
[Widget] Possibilità di scelta del numero dei record

### ISSUE THREAD

**Issue by Gabboxl** [Gabboxl/ClassevivaPCTO#202]
Aggiungere possibilità di scegliere la quantità voti/comunicazioni visualizzare nel widget

**Comment by alessandrocaseti** [comment]
- creare un expander con 2 sub-settingscard "Numero di elementi da visualizzare nei widget"
- ogni settings card contiene una combobox  "Numero di comunicazioni più recenti" & "Numero di valutazioni più recenti"
