### ISSUE TITLE
Problematica con le medie ponderate ovvero con la percentuale

### ISSUE THREAD

**Issue by MarcoGilardi2007** [Gabboxl/ClassevivaPCTO#205]
aprendo il programma quando si vanno a vedere le medie , il sistema fa la media tenendo conto in modo errato dei voti con una percentuale non 100% ad esempio una materia che ha la media del 7,7 se conta i voti con il 50 % la fa scendere a 5,6

**Comment by Gabboxl** [comment]
Ciao, hai ragione, grazie per la segnalazione. Verrà messo a posto a breve!

**Comment by Gabboxl** [comment]
Risolto con https://github.com/Gabboxl/ClassevivaPCTO/commit/894d1bf143b85ae8be7f9975974b0b3d22bda6d9
Verrà rilasciato a breve
