### ISSUE TITLE
[Valutazioni] Voto posto in alto a sinistra affianco a descrizione

### ISSUE THREAD

**Issue by Bananonz** [Gabboxl/ClassevivaPCTO#206]
Ho notato che se la descrizione del voto prende più di una riga il cerchiolino con dentro il voto va a posizionarsi al centro a sinistra della descrizione della valutazione, come si può vedere dalla seguente immagine:

![immagine](https://github.com/Gabboxl/ClassevivaPCTO/assets/70526508/0de87826-8a51-405b-9ad6-b189e34a16d2)

Secondo me sarebbe mgliore per una questione di ordine se si posizionasse in alto a sinistra, proprio affianco al nome della materia.

**Comment by Gabboxl** [comment]
Hai ragione, verrà messo a posto a breve. Grazie :)

**Comment by Bananonz** [comment]
Perfetto sono contento, posso chiudere oppure vuoi che lasci apero?

**Comment by Gabboxl** [comment]
> Perfetto sono contento, posso chiudere oppure vuoi che lasci apero?

Lascia pure così, chiuderò l'issue appena lo avrò risolto
