### ISSUE TITLE
[UI] All'avvio dell'app l'icona della Home nella NavigationView non è filled

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#224]

**Comment by alessandrocaseti** [comment]
non so a cosa è dovuto, ma l'app se aperta fuori da VS, come accennato sui commenti dell'altro issue, presenta il problema che le uniche pagine accessibili sono home e settings. Penso sia dovuto a questo fix, visto che era l'icona della home il problema. Ecco cosa vedo (le pagine che clicco non vengono caricate)
https://github.com/Gabboxl/ClassevivaPCTO/assets/90320229/36ecc670-f627-4d79-b540-2b0c31e4ab95

**Comment by Gabboxl** [comment]
> non so a cosa è dovuto, ma l'app se aperta fuori da VS, come accennato sui commenti dell'altro issue, presenta il problema che le uniche pagine accessibili sono home e settings. Penso sia dovuto a questo fix, visto che era l'icona della home il problema. Ecco cosa vedo (le pagine che clicco non vengono caricate) [Gabboxl/ClassevivaPCTO/assets/90320229/36ecc670-f627-4d79-b540-2b0c31e4ab95](https://github.com/Gabboxl/ClassevivaPCTO/assets/90320229/36ecc670-f627-4d79-b540-2b0c31e4ab95)
> 
> EDIT: se compilo l'app da vs però funziona tutto bene

già l'ho notato anche io sto problema, è tutto bello rotto se si avvia l'app normalmente
ora provo a mettere a posto

**Comment by alessandrocaseti** [comment]
> > non so a cosa è dovuto, ma l'app se aperta fuori da VS, come accennato sui commenti dell'altro issue, presenta il problema che le uniche pagine accessibili sono home e settings. Penso sia dovuto a questo fix, visto che era l'icona della home il problema. Ecco cosa vedo (le pagine che clicco non vengono caricate) [Gabboxl/ClassevivaPCTO/assets/90320229/36ecc670-f627-4d79-b540-2b0c31e4ab95](https://github.com/Gabboxl/ClassevivaPCTO/assets/90320229/36ecc670-f627-4d79-b540-2b0c31e4ab95)
> > EDIT: se compilo l'app da vs però funziona tutto bene
> 
> già l'ho notato anche io sto problema, è tutto bello rotto se si avvia l'app normalmente ora provo a mettere a posto

ok

**Comment by Gabboxl** [comment]
il problema non è la modifica per le icone, sembra essere qualcos'altro

**Comment by Gabboxl** [comment]
@alessandrocaseti il problema è introdotto col la tua modifica https://github.com/Gabboxl/ClassevivaPCTO/commit/f75cd628f45e7dea6390c7c51f31ad2cee6b67d3

molto probabilmente c'è qualcosa in App.xaml che non gli piace

**Comment by alessandrocaseti** [comment]
> @alessandrocaseti il problema è introdotto con la tua modifica [f75cd62](https://github.com/Gabboxl/ClassevivaPCTO/commit/f75cd628f45e7dea6390c7c51f31ad2cee6b67d3)
> 
> molto probabilmente c'è qualcosa in App.xaml che non gli piace
> 
> provo a mettere a posto

possibile forse è quel BasedOn dello stile del titolo? mi ricordo mi dava degli errori prima di compilarlo. Provo a vedere anche io adesso cosa è

**Comment by Gabboxl** [comment]
@alessandrocaseti corretto con	https://github.com/Gabboxl/ClassevivaPCTO/commit/b7deae5f16a027b5ed2c04d38ead70592189c3ce
in pratica il problema era la proprietà "TargetType" per lo stile "PageProgressRingStyle" che faceva riferimento a Windows.UI.Xaml.Controls.ProgressRing al posto di quello della libreria WinUI 2 Microsoft.UI.Xaml.Controls.ProgressRing.

Probabilmente in debug fa qualche magia strana per far funzionare tutto anche se fa riferimento a tipi diversi
