### ISSUE TITLE
[Crowdin] Aggiungere nuove lingue da poter tradurre

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#229]
Si potrebbero aggiungere rumeno, albanese, croato, portoghese e polacco

**Comment by Gabboxl** [comment]
aggiunte

**Comment by alessandrocaseti** [comment]
> Che succede? Crasha l'app?

da debug si, se la selezioni non succede nulla e non viene triggerato il dialogo. Dice che non trova langprogressperc
