### ISSUE TITLE
[Grades] Ricordare layout valutazioni

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#238]
Combobox per selezionare il layout predefinito della pagina valutazioni

**Comment by Gabboxl** [comment]
al posto del menu basta ricordare la scelta selezionata

**Comment by alessandrocaseti** [comment]
> al posto del menu basta ricordare la scelta selezionata

sarebbe il top, vedo se riesco a farlo, tanto tocca usare le solite funzione SaveAsync e ReadAsync giusto?

**Comment by Gabboxl** [comment]
> > al posto del menu basta ricordare la scelta selezionata
> 
> sarebbe il top, vedo se riesco a farlo, tanto tocca usare le solite funzione SaveAsync e ReadAsync giusto?

yes
