### ISSUE TITLE
[Code Quality] implementare x:Uid / binding nelle proprietà Path:Data delle icone degli hyperlink

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#240]
Rimpiazzare le lunghissime righe di data con un sistema di binding collegato al file untranslatable.resw

**Comment by Gabboxl** [comment]
useremo un altro sistema, come su fluentweather

**Comment by Gabboxl** [comment]
tra l'altro tra poco rimuoveremo tutti gli xbind in favore di un nuovo sistema di traduzione più flessibile, sarà estremamente utile per il caricamento dinamico delle risorse come per esempio da crowdin

**Comment by alessandrocaseti** [comment]
> tra l'altro tra poco rimuoveremo tutti gli xbind in favore di un nuovo sistema di traduzione più flessibile, sarà estremamente utile per il caricamento dinamico delle risorse come per esempio da crowdin

apposto meglio ancora, non vedo l'ora
