### ISSUE TITLE
[NoticeDialog] largezza titolo eccessiva

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#241]
![Screenshot (1)](https://github.com/Gabboxl/ClassevivaPCTO/assets/90320229/53c101a9-3da7-42ef-9f0b-52218c58dcf5)

**Comment by alessandrocaseti** [comment]
utilizzando la proprità maxwidth anziché width nella dichiarazione del dialog risolve il problema della larghezza, ma il dialog rimane allineato a sx
![image](https://github.com/Gabboxl/ClassevivaPCTO/assets/90320229/f36f746f-0ad1-4ba9-8a97-d9c49feed682)

**Comment by Gabboxl** [comment]
> utilizzando la proprità maxwidth anziché width nella dichiarazione del dialog risolve il problema della larghezza, ma il dialog rimane allineato a sx
> ![image](https://github.com/Gabboxl/ClassevivaPCTO/assets/90320229/f36f746f-0ad1-4ba9-8a97-d9c49feed682)
> 

Già, l'esistenza di questo problema è risaputa, purtroppo non c'è soluzione, l'unica via è il width

**Comment by alessandrocaseti** [comment]
> > utilizzando la proprità maxwidth anziché width nella dichiarazione del dialog risolve il problema della larghezza, ma il dialog rimane allineato a sx
> > ![image](https://private-user-images.githubusercontent.com/90320229/313419271-f36f746f-0ad1-4ba9-8a97-d9c49feed682.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MTYwMzIsIm5iZiI6MTcxMDYxNTczMiwicGF0aCI6Ii85MDMyMDIyOS8zMTM0MTkyNzEtZjM2Zjc0NmYtMGFkMS00YmE5LThhOTctZDljNDlmZWVkNjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE5MDIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZmVmYmE2OWRlZmQzOTBjNWI5ZThiYWM3NWRmNjAzMDMxNDc5MjI2Mzc4OGMxM2I5NjJlZGI5YjE4MjVjNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gJEcED9JdMBZINNbzFIURQGozURW_LonOPqqQte1Isk)
> 
> Già, l'esistenza di questo problema è risaputa, purtroppo non c'è soluzione, l'unica via è il width
> 
> Suppongo non verrà mai messa a posto perché lo sviluppo di winui 2 è ormai "concluso" in favore di winui 3

presumo si possia risolvere usando un titletemplate

**Comment by Gabboxl** [comment]
> > > utilizzando la proprità maxwidth anziché width nella dichiarazione del dialog risolve il problema della larghezza, ma il dialog rimane allineato a sx
> > > ![image](https://private-user-images.githubusercontent.com/90320229/313419271-f36f746f-0ad1-4ba9-8a97-d9c49feed682.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MTYwMzIsIm5iZiI6MTcxMDYxNTczMiwicGF0aCI6Ii85MDMyMDIyOS8zMTM0MTkyNzEtZjM2Zjc0NmYtMGFkMS00YmE5LThhOTctZDljNDlmZWVkNjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE5MDIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZmVmYmE2OWRlZmQzOTBjNWI5ZThiYWM3NWRmNjAzMDMxNDc5MjI2Mzc4OGMxM2I5NjJlZGI5YjE4MjVjNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gJEcED9JdMBZINNbzFIURQGozURW_LonOPqqQte1Isk)
> > 
> > 
> > Già, l'esistenza di questo problema è risaputa, purtroppo non c'è soluzione, l'unica via è il width
> > Suppongo non verrà mai messa a posto perché lo sviluppo di winui 2 è ormai "concluso" in favore di winui 3
> 
> presumo si possia risolvere usando un titletemplate

prova, se riesci sarebbe fantastico

**Comment by alessandrocaseti** [comment]
> > > > utilizzando la proprità maxwidth anziché width nella dichiarazione del dialog risolve il problema della larghezza, ma il dialog rimane allineato a sx
> > > > ![image](https://private-user-images.githubusercontent.com/90320229/313419271-f36f746f-0ad1-4ba9-8a97-d9c49feed682.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MTYwMzIsIm5iZiI6MTcxMDYxNTczMiwicGF0aCI6Ii85MDMyMDIyOS8zMTM0MTkyNzEtZjM2Zjc0NmYtMGFkMS00YmE5LThhOTctZDljNDlmZWVkNjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE5MDIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZmVmYmE2OWRlZmQzOTBjNWI5ZThiYWM3NWRmNjAzMDMxNDc5MjI2Mzc4OGMxM2I5NjJlZGI5YjE4MjVjNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gJEcED9JdMBZINNbzFIURQGozURW_LonOPqqQte1Isk)
> > > 
> > > 
> > > Già, l'esistenza di questo problema è risaputa, purtroppo non c'è soluzione, l'unica via è il width
> > > Suppongo non verrà mai messa a posto perché lo sviluppo di winui 2 è ormai "concluso" in favore di winui 3
> > 
> > 
> > presumo si possia risolvere usando un titletemplate
> 
> prova, se riesci sarebbe fantastico

eh non so come, tu hai tempo stasera? se puoi guarda anche le nuove pr e quelle pronte

**Comment by alessandrocaseti** [comment]
Hi everyone. I also struggled with this a while ago and i don't remember where i saw this but this problem has been "solved" a while ago. This has to do with the order of resource loading.
By default when installing WinUI nuget or creating a new Windows App SDK project, the App.xaml file is like this:

```
<Application
    x:Class="App1.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App1">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
                <!-- Other merged dictionaries here -->
            </ResourceDictionary.MergedDictionaries>
            <!-- Other app resources here -->
        </ResourceDictionary>
    </Application.Resources>
</Application>

problem is when you put your
   <x:Double x:Key="ContentDialogMaxWidth">9999</x:Double>
in the other app resources, somehow it gets loaded before the WinUI styles. and so it's ignored. To solve this, the WInUI team created a way to ensure their resources are loaded first and then yours so you can override them.

<Application
    x:Class="App1.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:controls="using:Microsoft.UI.Xaml.Controls"
    xmlns:local="using:App1" >
    <Application.Resources>
        <controls:XamlControlsResources>
            <controls:XamlControlsResources.MergedDictionaries>
                <ResourceDictionary>
                    <x:Double x:Key="ContentDialogMaxWidth">1000</x:Double>
                </ResourceDictionary>

            </controls:XamlControlsResources.MergedDictionaries>
        </controls:XamlControlsResources>
    </Application.Resources>
</Application>
```
Notice we now import the namespace
xmlns:controls="using:Microsoft.UI.Xaml.Controls"
and then our overrides go into a special "controls:XamlControlsResources"
This works flawlessly.

**Comment by alessandrocaseti** [comment]
fixato !!
![image](https://github.com/Gabboxl/ClassevivaPCTO/assets/90320229/4730e940-7ede-47ef-8d9f-97f7bb4b2754)

**Comment by alessandrocaseti** [comment]
> Grande! Come lo hai risolto?

nel fine settimana farò una pr con un sacco di cambiamenti questo incluso, comunque dal file app.xaml ho ridefinito la proprietà del ResDictionary. Ah una cosa, sei riuscito a capire come richiamare le risorse via XAML dal file untranslatable?

**Comment by Gabboxl** [comment]
> > Grande! Come lo hai risolto?
> 
> nel fine settimana farò una pr con un sacco di cambiamenti questo incluso, comunque dal file app.xaml ho ridefinito la proprietà del ResDictionary. Ah una cosa, sei riuscito a capire come richiamare le risorse via XAML dal file untranslatable?

non ho ancora visto niente, comunque ricordo di averla già provata la soluzione dell'app.xaml. non mi convince perchè lo applica su qualsiasi dialog questo max width, e ci saranno dialog che ci serviranno più grandi di quel max width nel futuro

**Comment by alessandrocaseti** [comment]
> > > Grande! Come lo hai risolto?
> > 
> > nel fine settimana farò una pr con un sacco di cambiamenti questo incluso, comunque dal file app.xaml ho ridefinito la proprietà del ResDictionary. Ah una cosa, sei riuscito a capire come richiamare le risorse via XAML dal file untranslatable?
> 
> non ho ancora visto niente, comunque ricordo di averla già provata la soluzione dell'app.xaml. non mi convince perchè lo applica su qualsiasi dialog questo max width, e ci saranno dialog che ci serviranno più grandi di quel max width nel futuro

fidati è anche tanto, ho messo 1000 ma in caso si può aumentare, considera era 9999
