### ISSUE TITLE
[Crowdin] errore di chiamata API nelle lingue Polacco e Albanese

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#261]
prova a cambiare lingua da debug

`Crowdin.Api.CrowdinApiException: 'Not Found'`

in

`var selectedCrowdingLangId = projectBase.TargetLanguages.Where(x => x.Locale.ToLower() == langcode)
 .Select(x => x.Id).FirstOrDefault();`

SOLO polacco e albanese
che facciamo le togliamo?

**Comment by Gabboxl** [comment]
Da correggere
