### ISSUE TITLE
[Valutazioni] localizzare periodi didattici

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#262]

**Comment by Gabboxl** [comment]
Mi sembra ne avessimo già parlato, i periodi didattici sono dinamici come la descrizione degli eventi di assenza, non conviene tradurli

**Comment by alessandrocaseti** [comment]
> Mi sembra ne avessimo già parlato, i periodi didattici sono dinamici come la descrizione degli eventi di assenza, non conviene tradurli

ah non ricordavo anche per i periodi, più che altro perché basterebbe un controllo e se I due sono uguali si parla di quadrimestri  altrimenti trimestre/pentamestre. Così al posto di 1 Q. e 2 Q. si potrebbero usare gli aggettivi "Primo" e "Secondo" e a questo punto tantovale localizzarli
