### ISSUE TITLE
correggere il valore dell'impraparato

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#282]
l'impreparato (i) vale 3 e non 5

**Comment by Gabboxl** [comment]
davvero? dove lo hai visto?

**Comment by alessandrocaseti** [comment]
> davvero? dove lo hai visto?

![20241024_081411.jpg](https://github.com/user-attachments/assets/0e25463e-8135-436e-b6b1-16a3925d8959)

**Comment by Gabboxl** [comment]
> > davvero? dove lo hai visto?
> 
> ![20241024_081411.jpg](https://private-user-images.githubusercontent.com/90320229/379638966-0e25463e-8135-436e-b6b1-16a3925d8959.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3ODg4OTMsIm5iZiI6MTcyOTc4ODU5MywicGF0aCI6Ii85MDMyMDIyOS8zNzk2Mzg5NjYtMGUyNTQ2M2UtODEzNS00MzZlLWI2YjEtMTZhMzkyNWQ4OTU5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDE2NDk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4OGNiM2E2ZjAzMzFhYWZhMTc0YTUxZTc2NmY5OTBhNmE2NmQ5ZDQ4NjJjZTE0MWNjY2E1ZTY5N2Q2YjYzMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._JxBdP6wpYSBNC6AzCrazfSXrd1ztgIIBBc8BC6Z-JU)

Ah immaginavo 😅, ora è a posto
