### ISSUE TITLE
non mantiene le credenziali 

### ISSUE THREAD

**Issue by Garlics07** [Gabboxl/ClassevivaPCTO#288]
**Infos (please complete the following information):**
 - Device model/manufacturer: [e.g. Razer Blade 15 2020]
 - Windows version + build: [e.g. Windows 10 20H2 Build 19xxx.xx]
 - PininOrario version: 

**Description of the bug:**
il bug consiste nel non mantenere le info di accesso

**To Reproduce:**
(clear steps to reproduce the behavior)
log in , close the app , and open it again

**Expected behavior:**
still be logged

**Screenshots:**

**Additional context:**

**Comment by Gabboxl** [comment]
Testato, da me funziona. Hai attivato la checkbox al login per salvare le credenziali?

**Comment by Garlics07** [comment]
Si ho provato ad attivare la checkbox ma nulla , windows 11 24h2 su lenovo thinkpad e16

**Comment by Gabboxl** [comment]
Hai provato a disinstallare e a reinstallare l'app?
Stai usando la versione scaricata dal Microsoft Store?

**Comment by Garlics07** [comment]
Provato a disinstallare e reinstallare e si sto usando la versione Microsoft store

**Comment by Gabboxl** [comment]
@alessandrocaseti tu hai qualche problema simile su Windows 11?

**Comment by alessandrocaseti** [comment]
> @alessandrocaseti tu hai qualche problema simile su Windows 11?

a me le credenziali hanno dato problemi con la versione compilata da visual studio. Quella delle store ha sempre funzionato.

**Comment by Gabboxl** [comment]
non riesco e non so come riprodurre questo problema, resterà finchè non mi accadrà anche a me

**Comment by Gabboxl** [comment]
è possibile che in alcuni casi vengano salvate nel credentials vault password multiple, ho fatto una correzione a riguardo per ovviare a questo problema temporaneamente https://github.com/Gabboxl/ClassevivaPCTO/commit/6141efb5f2b0e86428671a74ade42b6ff67fe622

ti avviso quando verrà rilasciata la nuova versione

**Comment by Gabboxl** [comment]
domani mattina sarà disponibile sul Microsoft Store la versione 1.3.2 con questa fix, se il problema persiste riapri l'issue
