### ISSUE TITLE
le icone della pagina corrente nella sidebar dovrebbero essere di tipo filled

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#34]
nel microsoft store, l'icona della pagina corrente nella sidebar è riempita. Si potrebbe replicare tale comportamento usando la stessa icona ma nel font fluentsystemiconsfilled per la pagina corrente.

**Comment by Gabboxl** [comment]
Implementato con https://github.com/Gabboxl/ClassevivaPCTO/commit/28532afad0a079da5a27e8229be7cb162b44fec7
