### ISSUE TITLE
l'opzione "Vota l'app nello Store" non restituisce alcun risultato

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#42]

**Comment by Gabboxl** [comment]
Strano, a me funziona

**Comment by alessandrocaseti** [comment]
a me non funziona, forse perchè l'app non è installata dallo store. Non saprei dare altra spiegazione. Appena pubblicherai una prossima release sullo Store la riscarico e ti faccio sapere.

**Comment by Gabboxl** [comment]
Ho ricontrollato da un altro PC e la schermata per valutare l'app funziona, anche dall'ultima build da codice. Se riesci, quando premi il pulsante, invia uno screenshot della sezione Output di Visual studio

**Comment by alessandrocaseti** [comment]
provato ed ecco cosa succede

![Screenshot (175)](https://github.com/Gabboxl/ClassevivaPCTO/assets/90320229/e0afb1a3-0661-46e8-bb98-220e5eaa8c96)

**Comment by Gabboxl** [comment]
> provato ed ecco cosa succede
> 
> ![Screenshot (175)](https://github.com/Gabboxl/ClassevivaPCTO/assets/90320229/e0afb1a3-0661-46e8-bb98-220e5eaa8c96)
> 

Se scorri in su ci sono altri messaggi?

**Comment by alessandrocaseti** [comment]
no, provando a spammare succede questo

![Screenshot (176)](https://github.com/Gabboxl/ClassevivaPCTO/assets/90320229/2f5fb4ca-5e9d-4284-a033-e8672bdba241)

**Comment by Gabboxl** [comment]
mhh non ho la minima idea di perchè ti succeda questo, farò un po' di ricerche. altrimenti per non rischiare che non funzioni anche ad altri leviamo il pulsante

**Comment by Gabboxl** [comment]
@alessandrocaseti continua a non funzionarti?

**Comment by alessandrocaseti** [comment]
hai fatto altre modifiche? se no non penso, appena torno ci guardo

**Comment by alessandrocaseti** [comment]
@Gabboxl continua a non funzionare

**Comment by Gabboxl** [comment]
> @Gabboxl continua a non funzionare

Nel microsoft store hai fatto il login?

**Comment by Gabboxl** [comment]
Aggiungo che da macchina virtuale con windows 11 il pulsante funziona, dovremmo magari trovare un metodo per segnalare un errore nel caso non si aprisse

**Comment by alessandrocaseti** [comment]
ho reinstallato l'app dallo store, adesso funziona. Sicuramente era un problema relativo al fatto che l'avevo disinstallata per compilarla manualmente
