### ISSUE TITLE
La pagina "assenze e ritardi" utilizza più memoria e rallenta le prestazioni

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#48]
scorrendo tra le varie pagine, quella riferita alle assenze e ai ritardi utilizza molta più memoria. Inoltre non si può cambiare pagina fino al caricamento completo delle assenze, cosa che non succede sulle altre pagine.

**Comment by Gabboxl** [comment]
Si hai ragione, purtroppo il blocco dell'interfaccia è dovuto al caricamento dei colori per i giorni del calendario. 
Riguardo a questo non si può far nulla purtroppo :(
