### ISSUE TITLE
Migliorare la posizione dei progressring

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#49]
I progressring sono sempre posizionati in alto a destra, non sarebbero meglio affianco al titolo della pagina? In caso è da fare una volta completato il refreshbutton globale #44

**Comment by alessandrocaseti** [comment]
anche quelli nella dashboard ad esempio, piuttosto che 3 progressring per ogni sezione uno affianco al titolo per che vale per tutte le sezioni

**Comment by Gabboxl** [comment]
Nella dashboard è meglio segnalare quale sezione si sta caricando siccome hanno tempi diversi di caricamento le varie schede, giusto per non dare l'impressione che si sia bloccato.

Nell'agenda lo metterò in alto come le altre sezioni
