### ISSUE TITLE
[Agenda] impossibile aprire il popup lezioni

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#55]
Da ormai due giorni continuo ad avere il problema "Errore di chiamata API, riprova più tardi". Non succedeva prima, molto strano
![Screenshot (168)](https://github.com/Gabboxl/ClassevivaPCTO/assets/90320229/6fbbe020-5455-40dd-83b1-5c4c5ca57d1d)

**Comment by Gabboxl** [comment]
Già strano anche a me, provo a dare un'occhiata

**Comment by Gabboxl** [comment]
Grazie, messo a posto con https://github.com/Gabboxl/ClassevivaPCTO/commit/373a56c6754d66e9a25f1ce340f51b834f5a3b39
