### ISSUE TITLE
[Palette] Finire le combinazioni di colori

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#58]
- aggiungere il colore per uscite/voti che non fanno media
- migliorare il layout dell'expander
- creare un'altra palette
- tooltips

**Comment by Gabboxl** [comment]
Aggiungere di nuovo i nomi delle palette nel combobox?

**Comment by alessandrocaseti** [comment]
si vanno aggiunti, ma non sopra i border, dovrebbe essere così:

Classeviva  O O O O
Palette 2    O O O O
Palette 3    O O O O

etc, intendo i nomi allineati a SX, mentre i border tutti allineati a DX

**Comment by Gabboxl** [comment]
@alessandrocaseti così ci sta? 
![image](https://github.com/Gabboxl/ClassevivaPCTO/assets/26819478/423537e6-3b08-418c-ac6d-7dd861506a1e)

**Comment by alessandrocaseti** [comment]
no, i borders dei colori devono essere tutti allineati a destra, uno sotto l'altro ma come una tabella.

**Comment by alessandrocaseti** [comment]
inoltre io toglierei il colore giallo, tanto è goldenrod per tutti, così ottimiziamo anche lo spazio. Magari in futuro lo rimettiamo

**Comment by Gabboxl** [comment]
> no, i borders dei colori devono essere tutti allineati a destra, uno sotto l'altro ma come una tabella.

ci ho provato a farlo per un'oretta ma non sembra possibile farlo, non è possibile "allungare" lo spazio all'interno degli elementi del combobox

![image](https://github.com/Gabboxl/ClassevivaPCTO/assets/26819478/d1ce5d00-cb79-4a96-84a8-599770280f1e)

**Comment by Gabboxl** [comment]
magari provo a chiedere su stackoverflow, forse qualcuno sa un modo per farlo

**Comment by alessandrocaseti** [comment]
va bene, al massimo lasciamo solo i border
