### ISSUE TITLE
[Valutazioni redesign] rendere funzionale refreshbutton in valutazioni + progressring

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#64]
dipende da #77

**Comment by Gabboxl** [comment]
progressring note implementato con https://github.com/Gabboxl/ClassevivaPCTO/commit/2ef6e90771669c942781f7d9f46bd980df9ca874

**Comment by Gabboxl** [comment]
implementato con https://github.com/Gabboxl/ClassevivaPCTO/commit/bb83fa395e72d55cd978b85ba042141a8b6e9c12 e https://github.com/Gabboxl/ClassevivaPCTO/commit/3d3c23610519ad90a2528c03a114963a143f990b
