### ISSUE TITLE
[Valutazioni redesign] SegmentedControl periodi didattici

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#73]
![voti redesign trimestre](https://github.com/Gabboxl/ClassevivaPCTO/assets/90320229/11e1fcf8-e64f-4233-9852-db678686f113)
![voti redesign](https://github.com/Gabboxl/ClassevivaPCTO/assets/90320229/11f2b9d2-94c2-45e8-8bd7-4884f43649f7)

**Comment by Gabboxl** [comment]
Implementato
