### ISSUE TITLE
[Valutazioni redesign] Sistema indicatori di variazioni di media

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#75]

**Comment by Gabboxl** [comment]
Come dovrebbe funzionare la variazione?  
1) Calcolo media dei voti della materia SENZA il voto più recente
2) Ricalcolo la media dei voti della materia ma con il voto più recente
3) vedo se la media è calata o salita

Così?

**Comment by alessandrocaseti** [comment]
semplicemente se la media sale l'indicatore è positivo, se scende negativo.

**Comment by Gabboxl** [comment]
> semplicemente se la media sale l'indicatore è positivo, se scende negativo. tutto tenendo conto dell'ultimo voto

ok si
