### ISSUE TITLE
[Assenze] rendere funzionale scrollbar listview assenze

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#79]

**Comment by Gabboxl** [comment]
Fare la card che contiene gli eventi assenze flessibile che si adatti ala dimensione della pagina

**Comment by Gabboxl** [comment]
La scrollbar funziona

**Comment by alessandrocaseti** [comment]
si ma hai messo che scrolla la listview e non la pagina?

**Comment by Gabboxl** [comment]
> si ma hai messo che scrolla la listview e non la pagina?

Si però devo ancora capire come gestire schermi piccoli/grandi in maniera che si espanda se lo schermo è abbastanza grande
