### ISSUE TITLE
Quando si cerca di aprire o salvare un allegato l'app si blocca

### ISSUE THREAD

**Issue by aledezzy** [Gabboxl/ClassevivaPCTO#81]
Quando si cerca di aprire un pdf o un qualsiasi allegato in bacheca o negli scrutini l'app si blocca e rimane così. 
![bug](https://github.com/Gabboxl/ClassevivaPCTO/assets/65111581/0dcc386e-4561-471c-9ea2-f7527ae2206b)

**Comment by Gabboxl** [comment]
Ciao, questo bug è già stato segnalato ed è risolto, ma non ancora pubblicato. 
Attualmente stiamo finalizzando alcune altre grandi modifiche che verranno pubblicate in un grosso aggiornamento prima dell'inizio della scuola.
Se vuoi puoi dare un'occhiata scaricando il codice dell'app e compilandolo te stesso :)

**Comment by aledezzy** [comment]
Ok, grazie mille!
Ottimo progetto comunque ragazzi, davvero complimenti!
