### ISSUE TITLE
rendere traducibili le ultime strings

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#83]
- [x] Comunicazioni - "Valida dal ... al"
- [x] Comunicazioni - "Scaduta" "Eliminata"
- [x] Scrutini - "Non disponibile"
- [x] Settings - Dialog "sei sicuro di voler uscire"
- [x] Settings - dialog "Riavvio richiesto"
- [x] nei titoli "Dashboard di Alessandro" o "Valutazioni di Alessandro" si riuscirebbe a mettere il nome prima in modo da usare il genitivo sassone "Alessandro's Dashboard" etc? altrimenti leviamo direttamente il nome e lasciamo solo Dashboard

**Comment by Gabboxl** [comment]
> nei titoli "Dashboard di Alessandro" o "Valutazioni di Alessandro" si riuscirebbe a mettere il nome prima in modo da usare il genitivo sassone "Alessandro's Dashboard" etc? altrimenti leviamo direttamente il nome e lasciamo solo Dashboard

Cavolo non ci ho pensato

C'è un metodo che non ricordo come si chiama però, appena lo trovo implemento

**Comment by Gabboxl** [comment]
https://stackoverflow.com/questions/1008966/c-sharp-how-to-add-placement-variable-into-a-resource-string

`String.Format("ciao {0}", nome);`

**Comment by Gabboxl** [comment]
implementazione di prova in https://github.com/Gabboxl/ClassevivaPCTO/commit/9823a781d7c0c6a27d6409bcc3c9951ddeb75767

da fare con il resto delle stringhe

**Comment by alessandrocaseti** [comment]
@Gabboxl direi di togliere il nome dell'utente dal titolo della pagina valutazioni, lasciamo solo il testo "valutazioni", anche perché sennò il nome dovrebbe essere incluso in tutte le pagine, casomai lasciamolo solo nel titolo della dashboard

**Comment by Gabboxl** [comment]
> @Gabboxl direi di togliere il nome dell'utente dal titolo della pagina valutazioni, lasciamo solo il testo "valutazioni", anche perché sennò il nome dovrebbe essere incluso in tutte le pagine, casomai lasciamolo solo nel titolo della dashboard

si sono d'accordo, lo levo

**Comment by Gabboxl** [comment]
fatto
