### ISSUE TITLE
[Scrutini] Aggiungere nome sezione "Report scolastici" nella sezione scrutini

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#84]
aggiungere il testo "report scolastici" prima della listview dei medesimi elementi. Stessa formattazione del testo "documenti"

**Comment by Gabboxl** [comment]
https://github.com/Gabboxl/ClassevivaPCTO/commit/7b764862b6c8188f4f2cf41bbdf4d90326f2d97d
