### ISSUE TITLE
Resettato l'anno scolastico, persistono gli errori di chiamata API

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#86]
almeno i placeholder "nessun evento, documento, lezione, voto etc.." dovrebbero essere disponibili

**Comment by Gabboxl** [comment]
```
{
    "statusCode": 503,
    "error": "112:CvvRestApi/school year not started yet",
    "message": "you can only access from previous school year",
    "where": "RestCommons #266"
}
```

**Comment by Gabboxl** [comment]
questo è un problema, non posso più testare la nuova pagina valutazioni

**Comment by Gabboxl** [comment]
scherzavo purtroppo, non funzionano neppure le api degli anni passati. finchè non funzionano di nuovo non posso continuare lo sviluppo della sezione valutazioni :(

**Comment by Gabboxl** [comment]
Gli errori chiamata API li lasciamo, così facciamo capire che è un problema del server se non si vedono i dati nell'app. Metteremo comunque i placeholder per le sezioni con dati mancanti.
