### ISSUE TITLE
aggiungere placeholders mancanti

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#88]
- [x] nessuna valutazione
- [x] nessuna lezione
- [x] nessun compito
- [x] nessun documento / report scolastico oppure "scrutini non disponibili"
- [x] nessuna assenza

Edit: ovviamente stessa formattazione degli altri

**Comment by Gabboxl** [comment]
nessun compito/lezione intendi nel contesto dei popup?
