### ISSUE TITLE
[Agenda] Min/Max date nel calendardatepicker

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#89]
cliccando nel CalendarDatePicker una data che non appartiene all'anno scolastico corrente ovviamente restituisce errore di chiamata API. Si potrebbe ovviare a ciò utilizzando le proprietà `MinDate` e `MaxDate`. Queste potrebbero variare a seconda dell'anno scolastico, ad esempio se è selezionato l'A.S. 2023/24 la MinDate corrisponderà al 01/09/23, mentre la MaxDate al 31/08/24 e così via.

**Comment by alessandrocaseti** [comment]
![Screenshot (185)](https://github.com/Gabboxl/ClassevivaPCTO/assets/90320229/35e94e8f-a092-4b67-b669-6768f98bb5dc)
comunque piuttosto che correggere l'errore direi di utilizzare min e max date, almeno lo evitiamo di sicuro e forse aumenta anche le prestazioni

**Comment by Gabboxl** [comment]
> ![Screenshot (185)](https://user-images.githubusercontent.com/90320229/265729006-35e94e8f-a092-4b67-b669-6768f98bb5dc.png) comunque piuttosto che correggere l'errore direi di utilizzare min e max date, almeno lo evitiamo di sicuro e forse aumenta anche le prestazioni

Questo errore è ancora quello legato al cambio dell'anno scolastico, però si, dovrebbe dare comunque errore se si seleziona una data al di fuori del range scolastico
