### ISSUE TITLE
[Promemoria per la 1.0.0] aggiornare screenshot sullo store, descrizioni e readme

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#90]

**Comment by Gabboxl** [comment]
Cosa dovremmo aggiornare nel readme? E nelle descrizioni?

**Comment by alessandrocaseti** [comment]
aggiungere gli screenshots, lista delle features e roadmap. Mettiamo in evidenza le features che non sono presenti sull'app mobile

**Comment by Gabboxl** [comment]
@alessandrocaseti se hai tempo avresti voglia di fare tu i nuovi screenshot per la pagina dello store? tipo stile minimal con titoli di presentazione delle varie sezioni

**Comment by alessandrocaseti** [comment]
settimana prossima avrò tempo, lo faremo appena rilasciata la v1

**Comment by Gabboxl** [comment]
> settimana prossima avrò tempo, lo faremo appena rilasciata la v1

ottimo, appena ce li hai pronti manda pure qua o su ds

**Comment by Gabboxl** [comment]
@alessandrocaseti strafigo il readme con il nuovo logo, grande
