### ISSUE TITLE
ultimare le traduzioni

### ISSUE THREAD

**Issue by alessandrocaseti** [Gabboxl/ClassevivaPCTO#96]
- [x] aggiungere nomi delle lingue nella combobox
- [x] [Login] bottone "Accedi"
- [x] nuova pagina valutazioni (checkbox, seg.control...)
- [x] dialog "errore di chiamata API"
- [x] placeholders nuovi #88 
- [x] report scolastici #84 
- [x] tutorial
- [x] changelog

ultimare tutto + correggere titolo bacheca

**Comment by Gabboxl** [comment]
> aggiungere dialog "lingua attualmente non disponibile" con magari hyperlink a crowdin per quando nella combobox si selezionano francese, spagnolo e tedesco

Questo purtroppo non possiamo capirlo dal codice se la lingua è stata tradotta o meno, piuttosto leviamo le lingue che non sono pronte.

**Comment by alessandrocaseti** [comment]
senza capirlo dal codice, mettiamo noi il dialog e lo togliamo quando sappiamo che la lingua è pronta. Magari alcuni utenti conoscono quella lingua e saranno motivati a tradurla vedendo che non è disponibile

**Comment by Gabboxl** [comment]
Anzi, esistono le api di Crowdin che possiamo usare per prendere la percentuale di traduzione, se non fosse 100% invitiamo l'utente a tradurre con un dialog

**Comment by alessandrocaseti** [comment]
sarebbe il top
